[BE] feat: 사전메일 전송 기능을 구현한다.
woowacourse-teams/2022-ternoko pull request #136
Opened 2022-08-02 07:00 UTC by dongho108

### Issues
- [ ] #120 

### 논의사항
- 스프링 스케줄러의 cron으로 매일 23시 59분에 메일이 발송되도록 구현했습니다.
- 메일전송 테스트는 실제 라이브러리의 send메서드를 호출하는지 mock으로 검증했습니다.
- 메일전송을 테스트해보고 싶으시면 
   1. DataInitializer에서 코치의 이메일을 수정하고
   2. yml에서 계정 비밀번호를 수정하고
   3. cron의 시간을 변경하거나 테스트에서 실제로 send하는 메서드(mock 대신에) 호출하면 됩니다.

close #120

2022-08-09 03:20 UTC, soominsohn reviewed
안녕하세요 애쉬, 열음!
사전메일 전송 기능 굉장히 어려웠을 로직인데, 고생 많으셨습니다.
코멘트 몇개 남겼습니다. 확인 부탁드릴게요. 😄 
남겨주신
```
mailSender는 외부 라이브러리라서 구분하고싶었는데 메세지를 generate 하는 부분이 sender안에 있어서
면담 사전질문 내용같은 것들이 sender에 포함되어있습니다.
의존성을 끊는게 맞는지 끊을려면 어떻게 해야하는지 고민됩니다!
```
에 대해서는 이미 사전질문 내용이 dto로 감싸져 sender가 사용하고 있기 때문에, 큰 문제없다가 제 의견입니다.

만일 의존성을 끊고 싶다면,
```
        message.setFrom(emailDto.getFrom());
        message.setTo(emailDto.getCoachEmail());
        message.setSubject(subject);
        message.setText(content);
```
message의 setter 메서드에 가는 string을 모두 generate() 메서드를 호출하는 곳에서 정제한 후, 파라미터로 담아 넘겨주는 것도 하나의 방법이라고 생각합니다! 
어떤 방법이 좋을지는 고민이 더 필요하겠군요!

고생 많으셨습니다. 감사합니다. 😄

2022-08-09 03:20 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/support/EmailSender.java
> +                                emailDto.getCrewNickname()))
혹시 stringBuilder와 contentBuilder를 나누신 이유가 있으실까요?
혹시 초기화 때문이라면, 다음처럼 생성자로 초기화가 가능한걸로 알고있습니당!
그렇다면 객체생성을 한번 줄일 수 있을 것 같아요 😄 
```
final StringBuilder stringBuilder = new StringBuilder(String.format("안녕하세요 %s. %s 면담신청 합니다",
                emailDto.getCoachNickname(),
                emailDto.getCrewNickname()))
                .append(NEW_LINE)
                .append(String.format("면담 일시 : %s", dateFormat.format(emailDto.getInterviewStartTime())))
                .append(NEW_LINE)
               ......
```

2022-08-09 03:20 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
> +    private void setTimeZon(final TimeZone timeZone) {
`setTimeZon`에서 오타가 난 것 같습니다. e 가 빠진 것 같아요ㅎㅎ 감사합니다 🙇

2022-08-09 03:45 UTC, her0807 requested changes
메일 기능이 처음이었음에도 불구하고 고민하고 작성한게 느껴져서 저도 새로운 키워드를 찾아보고 재밌었어요 리뷰 내용은 제안일 뿐이니, 전부다 반영하시지 않아도 좋아요! 😁

2022-08-09 03:45 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/TernokoApplication.java
> +@EnableScheduling
SpringScheduler 를 사용하기 위해서 @EnableScheduling 어노테이션을 붙여야 `@Import(SchedulingConfiguration.class)` 이 설정되면서, 스케줄링이 활성화가 되고, @Scheduled 로 작업을 활성화 시킨다. 가 동작 원리 인 것 같은데.

@EnableScheduling 의 위치가 조금 고민되네요. 

고민이 되는 이유는 스케줄링 활성화가 되면 분명 side effect 가 있을 것 같다고 예상되는데, 관련 레퍼런스를 찾을 수가 없어서 답답S .. 합니다 ㅎㅎㅎ 같이 고민해주세요 !!!


1) 현재 위치를 유지한다.
2)이 해당 작업을 진행하는 EmailSender class 위에 위치한다.

2022-08-09 03:45 UTC, her0807 commented on backend/src/test/java/com/woowacourse/ternoko/fixture/CoachAvailableTimeFixture.java
LocalDateTime 은 가변하는 성질이 있어서 `Clock` 을 사용하는 것으로 변경해보면 어떨까요 ? 

천천히 리팩토링 .. ㅎㅎ 


https://stackoverflow.com/questions/39527752/how-to-test-date-created-with-localdatetime-now

2022-08-09 03:45 UTC, her0807 commented on backend/src/test/java/com/woowacourse/ternoko/service/EmailServiceTest.java
> +
애쉬가 지난번에 메일 관련한 test 로직이 고민이라고 얘기해주었던게 생각나네요. 

저도 같이 고민해보았는데요, 이메일이 무사히 잘 갔는지 까지는 검증이 어려운 것 같고, 현재 처럼 보내는 요청을 카운팅 하는 방식이 좋을 것 같아요.  굿 👍🏻

2022-08-09 03:58 UTC, HyeonbinSa reviewed
사전 메일 어려운 기능 구현하시느라고 고생 많으셨습니다.

2022-08-09 03:58 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/TernokoApplication.java
> +@EnableScheduling
- tutorialspoint.com - [링크](https://www.tutorialspoint.com/spring_boot/spring_boot_scheduling.htm)
이곳을 확인해보니까 초반 부분에 
"The @EnableScheduling annotation is used to enable the scheduler for your application. This annotation should be added into the main Spring Boot application class file."

Main Spring Boot application 클래스 파일에 위치하여 사용하라고 명시되어있는 것 같습니다.

2022-08-09 03:58 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/service/EmailService.java
> +        final LocalDateTime localDateTimeOfNextDay = LocalDateTime.now().plusDays(1);
개인적인 취향인 것 같지만 저는 Tomorrow는 내일, NextDay는 다음날 과 같은 늬앙스로 느껴져서 다음날이 조금 더 어울리는 것 같습니다.

2022-08-11 05:54 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/dto/ReservationResponse.java
> +                .interviewQuestions(formItemRespons)
👍

2022-08-11 23:36 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
> +        setTimeZon(TimeZone.getTimeZone(KST));
😄

2022-08-11 23:44 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/Interview.java
> +    }
인터뷰의 상태를 검증하는 상황이 여러개 생길 것 같아서 미리 주입받는 형식으로 고쳤는데요.

지금은 update 시에 FIX이면 예외를 반환하는 한가지 상황만 있습니다.
하지만 추후에 feedback(지금은 comment니까 상태명이 바뀌겠지요)

```java
public enum InterviewStatusType {
    EDITABLE,
    FIX,
    FEEDBACK,
    COMPLETED,
    CANCELED
}
```

예를들어
feedback이 완료되지 않은 상태에서 완료된 상태로 변경할경우?
feedback이 완료되지 않은 상태에서 수정할경우?
등과 같은 여러 상태검증상황이 나올 거 같아서 미리 분리해놓았습니다.

상황이 나오면 그때 리팩토링하는게 나을까요? 아니면 이미 분리를 해놨으니 그냥 두는 것이 나을까요?

2022-08-11 23:44 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/support/EmailSender.java
> +                .append(System.lineSeparator())
굿 ㅎ

2022-08-11 23:52 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/domain/Interview.java
> +    }
Boolean 처럼 두가지에 국한된 상태를 가진다면 메소드명에 명시적으로 적어주는게 좋으나 현재는  Interview가 여러개의 상태를 가지고 있고  계속해서 바꿔주어야하니 범용적으로 사용할 수 있는 메소드를 구현하는 것이 좋겠다고 생각했습니다. 바니는 이에대해 어떻게 생각하시나요?

2022-08-11 23:53 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/support/EmailSender.java
> +                                emailDto.getCrewNickname()))
좋은 방식 알려주셔서 감사합니다!!
그런데 생성자 안쓰고도 객체생성은 한번으로 줄일 수 있더라구요! 수정해봤습니다.

2022-08-11 23:54 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/domain/Interview.java
> +                                         final ExceptionType exceptionType) {
위에 바니가 남겨주신 코멘트와 동일한 내용인 것 같습니다:) 저와 애쉬가 댓글을 남겼으니 한번 확인부탁드려요.

2022-08-11 23:54 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/InterviewStatusException.java
> +    public InterviewStatusException(final ExceptionType exceptionType) {
ㅎㅎ 다른이슈에서 진행했습니다!

2022-08-11 23:57 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/TernokoApplication.java
> +@EnableScheduling
첨언하자면 SpringbootApplication 클래스 파일에 어노테이션을 붙이더라도 활성화는 @scheduled 로 하는 것으로 알고있습니다. 해당 어노테이션은 cron 작업이 필요한 메소드 위에 붙이는 거구요! 혹시 수달이 생각하신 side effect 가 있다면 어떤 것이 있을까요?

2022-08-12 06:04 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/fixture/CoachAvailableTimeFixture.java
다음 이슈에서 진행하겠습니다!

2022-08-12 10:00 UTC, closed without merging