[BE] feat: formItem의 question, answer 길이 검증 추가
woowacourse-teams/2022-ternoko pull request #182
Opened 2022-08-09 05:40 UTC by dongho108

### Issues
- [ ] #176 

### 논의사항
- 사전질문 길이 제한은 255, 답변 길이제한은 1000으로 제한했습니다.
- answer, question을 VO로 분리하고 검증책임을 부여했습니다.

close #176

2022-08-09 06:44 UTC, Juhyung990122 requested changes
안녕하세요 애쉬! 추가하신 내용 확인하고 간단한 코멘트 달아두었습니다.
한번 확인해주세요. 수고하셨습니다!

2022-08-09 06:44 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Answer.java
> +    @Column(length = 1000, nullable = false)
1000자 제한이 있다면 사용성 측면에서 보았을때 프론트에서도 글자수를 세어주는 기능이 추가로 필요할 것 같네요. 프론트에서 공수가 많이 드는 작업이거나, 특별히 길이를 제한하는 이유가 없다면 답변 길이 제한을 없애는 것도 좋은 방법일 것 같습니다:)

2022-08-09 06:44 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Question.java
> +    private String question;
바깥에서 접근할때 question.question이 될 것 같은데 변수명을 바꿔보는 것도 좋을 것 같습니다!🤔

2022-08-09 06:44 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Question.java
> +        }
validate 코드는 메소드로 분리해서 관리해도 좋을 것 같아요!

2022-08-09 07:22 UTC, her0807 commented
@dongho108 오늘 저녁 10시 전까지 리뷰 하겠습니다

2022-08-09 12:07 UTC, soominsohn reviewed
안녕하세요 애쉬! 면담의 질문과 답변을 객체로 잘 분리하셨군요! 고맙습니다 😄 
그러나 현재 애쉬의 레포지토리에서 `feat/backend/formItem-length-#176` 해당 브랜치가 fetch가 잘 안되네요! 내일 도와주실 수 있을까요? 일단 커밋 내역 보며 리뷰 남겼고, 나머지는 프로젝트 직접 돌려보고 남기겠습니다!

2022-08-09 12:07 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/FormItem.java
> +    private Answer answer;
Embedded 어노테이션 👍

2022-08-09 12:07 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/FormItem.java
> +        if (getId() != null ? !getId().equals(formItem.getId()) : formItem.getId() != null) {
FormItem, Answer, Question의 equals와 hashCode()를 재정의 해주셨군요!
그러나 현재 프로젝트에서 equals가 쓰이지 않고 있는 것 같아요 😢 
혹시 어떠한 이유로 재정의 하셨는지 알 수 있을까요?

2022-08-10 07:52 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/FormItem.java
> +        if (getId() != null ? !getId().equals(formItem.getId()) : formItem.getId() != null) {
@EqualsAndHashCode 를 사용해도 좋을 것 같아요. ✨

2022-08-12 01:52 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Answer.java
> +    @Column(length = 1000, nullable = false)
넹 저번에 회의한대로 수정할게요

2022-08-12 03:46 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Question.java
> +    private String question;
맞아요! 수정하겠습니다.

2022-08-12 03:55 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Question.java
> +    private String question;
처음엔 `value`로 했다가 컬럼명에 `value`가 안들어가는 이슈때문에 `content` 라는 변수명으로 바꿨습니다!

2022-08-12 04:02 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Question.java
> +    private String question;
와;;
FormItem에 Answer와 Question이 있는데 둘다 변수명이 같아서 같은 컬럼명으로 생성할 수 없는 에러였습니다.
@Column 어노테이션을 이용해 컬럼명을 다르게 생성시키고 변수명은 value로 이용할 수 있도록 수정했습니다.

2022-08-12 04:03 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/Question.java
> +        }
어.. 이 부분은 저도 메서드 분리하는 방식도 자주사용하긴 하는데요.
길이 비교하는 간단한 검증이다보니 굳이 분리를 안해도 가독성을 해치지 않고 오히려 가독성이 좋다라고 느껴져서요!
그래도 분리하는게 더 나을 것 같다는 의견이 있으면 수정하겠습니다.

2022-08-12 04:06 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/FormItem.java
> +        if (getId() != null ? !getId().equals(formItem.getId()) : formItem.getId() != null) {
원시값 포장과 VO의 개념에 대해 정확히 인지하지 못하고 있었습니다.

VO는 동등성을 보장시키기 위해 equals&hashCode를 오버라이드하지만, 원시값 포장을 위한 목적에서는 굳이 구현할 필요가 없다고 생각이 듭니다.

삭제합니다!

2022-08-12 04:07 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/domain/formitem/FormItem.java
> +        if (getId() != null ? !getId().equals(formItem.getId()) : formItem.getId() != null) {
게다가 Answer, Question이 아닌 FormItem에 구현했네요; 위치도 잘못되어있었습니다.

2022-08-12 04:12 UTC, dongho108 commented
### 컬럼명중복해결

### 원시값포장 vs VO
https://hyeon9mak.github.io/is-same-wrapping-class-and-VO/

2022-08-12 10:00 UTC, merged