[BE] feat: Comment Create 기능 구현 및 테스트 추가
woowacourse-teams/2022-ternoko pull request #231
Opened 2022-08-12 16:06 UTC by HyeonbinSa

### Issues
- [ ] #220 

### 논의사항
1.  MemberType enum 클래스를 활용하여 사용가능한 InterviewStatusType 가지고오는 로직 괜찮은지?
2. COMPLETE를 3가지(CREW_COMPLETE, COACH_COMPLETE, COMPLETE)로 분리하는 것이 괜찮은지?
    - [디스커션](https://github.com/woowacourse-teams/2022-ternoko/discussions/230)에 작성해둠.
3. Role 검증 로직은 추후 AccessToken에 Role 추가 시 변경될  가능성 높음.
4. Exception 네이밍 검토 요청
5. JPA 구현 방식
    - 처음 구현 방향 : Interview의 FormItem처럼 양방향 연관관계를 사용하려고 했음. -> 아래와 같은 이유로 실패
        - 이유 1
            - Interview에  Comment는 Crew, Coach 소유로 각각 2개가 존재하게됨.
            - OneToOne  관계로 매핑할 경우 Comment가 Member를 필드로 가지고 있어 Coach, Crew를 구분할 수 없음.(특히 column명으로)
        - 이유 2
            - Interview에 List<Comment>로 List<FormItem>처럼 가지고있는 방식
            - Comment는 Member를 가지고 있기 때문에  Crew, Coach 구분불가하여 List<Comment>에서는 확인할  수 없음(검증하는 로직이 추가되어야함)
    - 현재 구현 방식
        - Comment에게 @ManyToOne으로 단방향 다대일 연관관계 매핑  -> Interview는 Comment에 대해  모름
        - 현재 히스토리에서도 Comment, Interview 따로 호출하기 때문에 위와 같은 방식 채택

위와 같은 논의 사항이 있으니 확인 부탁드리며 중점적으로 코드리뷰 부탁드리며 의견 부탁드리겠습니다.
추가로 이 PR 이후로  Comment에 대해 조회 및 수정 기능을 구현할 예정이며 구현 후 리팩터링 및 코드 리뷰 반영하도록하겠습니다.

### 기능 요구 사항
- [x] [코치/크루] 끝난 면담에 대해 자유로운 한마디(Comment)를 남길 수 있다.
    - [x] 코치가 남길 경우 COACH_COMPLETE
    - [x] 크루가 남길 경우 CREW_COMPLETE
    - [x] 모두 남길 경우 COMPLETE 
         - COMPLETE가 없다면 COACH_COMPLETE  -> CREW_COMPLETE -> COACH_COMPLETE -> ... 반복되기 때문에 계속해서 작성할 수 있는 상황이 됨.
         - 데이터베이스 저장 시에 예외가 발생할 수 있고 Interview_id를 통해 조회 결과가 2이면 검증할 수 있으나 상태 변경을 통해서 완료를 표시하는 것이 프론트 쪽에서 확인할 때 편할 것 같다는 생각.
- [x] 예외
    - [x] 코치/크루는 하나의 인터뷰에 하나의 Comment만 남길 수 있다.
    - [x] COMMENT가 아닌 Status에서는 예외를 발생한다.
    - [x] Comment를 작성하려는 Interview가 존재하지 않는다면 예외를 발생한다.
    - [x] Comment를 작성하는 Member가 Interview의 Coach나 Crew 중 없다면 예외가 발생한다.
close

2022-08-12 16:20 UTC, HyeonbinSa commented
upstream -> develop에 fetch, rebase하는 과정에서 발생한 Conflict가 발생했습니다.
모두 해결했는데 push upstream이 안되서 force push 했으니 이부분도 다시 한번 확인 부탁드리겠습니다.

2022-08-13 13:52 UTC, her0807 requested changes
바니 ~ Interview 상태에 따른 Comment create 구현 정말 어려웠을텐데 잘 구현해주셨어요. 아래 코멘트는 주관적인 생각도 많이 담겨 있어서 바니가 원하시는 부분만 반영해주시면 좋겠어요. 주말에도 수고 많으셨습니다. 감사합니다🙇🏼‍♀️

2022-08-13 13:52 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/interview/domain/Interview.java
> +
상태가 2개 정도일 때는 괜찮았는데, 요구사항이 비대해지면서 점점 분기문이 많아졌네요 ㅠㅠㅠ

상태패턴으로 구현해보면 좋겠네요. 해당 작업이 어려울 것 같아서. 내일 오후 2시 전까지 직접 작업해보고 
해당 내용에 대한 제 생각 공유드리겠습니다. 작업하는데 엄청 머리 아프셨겠어요.

2022-08-13 13:52 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +    private Member getMember(Long memberId, Interview interview) {
해당 로직은 Comment 를 작성한 주체가 누구인지 파악하기 위한 로직인 듯합니다. ☺️

`findCoachOrCrewById` 로 네이밍을 수정한다면, 행위를 파악하기 더 수월해보여요!  ㅎㅎ

2022-08-13 13:52 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +    private MemberType getMemberType(final Long memberId) {
`findMemberType()`; 어떠십니까 ?

2022-08-13 13:52 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +        throw new MemberNotFoundException(INVALID_INTERVIEW_MEMBER_ID);
Exception good!

2022-08-13 13:52 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +        }
1) 검증 로직 매서드로 추출해서 관리하면 좋을 것 같아요.

MemberType 이 가질 수 있는 InterviewStatusList 를 반환받아서 Service 에서 Contains 보다 해당 상태를 MemberType 이 가지고 있는지 물어보면 어떨까요 ?

만약 그렇게 바꾼다면 아래와 같이 바꿀 수 있을 것 같아요.

```java

public enum MemberType {
    COACH,
    CREW;

    private static final List<InterviewStatusType> CREW_HAS_INTERVIEW_STATUS = List.of(InterviewStatusType.COMMENT,
            InterviewStatusType.CREW_COMPLETED);
    private static final List<InterviewStatusType> COACH_HAS_INTERVIEW_STATUS = List.of(InterviewStatusType.COMMENT,
            InterviewStatusType.COACH_COMPLETED);

    public boolean matchType(final String value) {
        return this.name().equals(value.toUpperCase(Locale.ROOT));
    }


    public boolean isValidInterviewStatusByMemberType(InterviewStatusType interviewStatusType) {
        if (this == COACH) {
            return CREW_HAS_INTERVIEW_STATUS.contains(interviewStatusType);
        }
        return COACH_HAS_INTERVIEW_STATUS.contains(interviewStatusType);
    }
}

```


```java

       if (!memberType.isValidInterviewStatusByMemberType(interview.getInterviewStatusType())) {
            throw new InvalidStatusCreateCommentException(INVALID_STATUS_CREATE_COMMENT);
        }

```

2022-08-13 13:52 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/comment/domain/Comment.java
> +)
join column unique 설정 어려웠을텐데, 잘해주셨네요. 👍🏻

2022-08-14 01:27 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/interview/domain/Interview.java
> +
저도 동의합니다. 하지만 저희가 사용하는 상태가 적은 수가 아니라 구현하려면 고민이 필요할거같아서 추후 리팩터링 과정에서 하면 좋을 것 같아요.
제가 생각해본 문제는 JPA를 사용해서 구현하고있는데 상태 패턴이라면 또 하나의 테이블이 생성되는거 아닌가 생각이 됐습니다.. 
좋은 의견 감사드려요

2022-08-14 01:28 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
> +
Acceptance 테스트는 비교적 적은 테스트만 수행했네요...
마지막 리팩터링 과정에서 클래스의 분리가 이뤄져서 리팩터링 단계에서 테스트 코드 추가해보도록하겠습니다.

감사합니다.

2022-08-14 01:31 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +        }
좋은 의견 감사합니다. 
수달, 고민 많이 하신거같아 감사드립니다. 
저도 작성하면서 같은 고민을 했는데 말씀해주신대로 수정해보았다가 현재는 InterviewStatusType에서 검증하도록 수정해보았습니다.
(리팩터링 PR에 적용되어있습니다.)

2022-08-14 01:52 UTC, HyeonbinSa commented
현재 PR에서 수정하기 어려운 내용들은 마지막 PR 이슈에 작성하였습니다.
이후 PR에서 수정되는 부분도 있고 Conflict 가능성이 많아 리팩터링 과정에서 처리하도록하겠습니다.
- 이슈 #232 - [링크](https://github.com/woowacourse-teams/2022-ternoko/issues/232)

2022-08-14 06:21 UTC, dongho108 requested changes
바니! 코멘트 추가 기능 구현하시느라 정말 고생 많으셨습니다!!!

코멘트가 좀 많은데 반영하기 힘들거나 이해 안가는 부분 있으시면 언제든지 물어봐주세요!! 
아니면 같이 반영해봐도 좋을 것 같아요!

수정되면 한번 더 리뷰요청 부탁드립니다. 😊

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/acceptance/InterviewAcceptanceTest.java
> +        assertThat(InterviewResponses).hasSize(3); // data.sql에 들어가있는 테스트 때문에 1 추가
자바코드에서도 interview가 추가해되고 ddl에서도 interview가 있어서 테스트 코드 짤 때 개수를 계속 신경써줘야 하는 부분이 불편할 수 있겠다 생각드네요.. ㅠ
ddl에서 데이터를 꼭 추가해주어야 하는 이유가 있었을까요?

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
> +public class CommentAcceptanceTest extends AcceptanceTest {
새롭게 추가된 API들에 대해서 restDocs도 추가해주셨을까요?

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
> +    }
comment create controller에서 commentId가 반환된다면 이 부분도 수정이 될 것 같습니다!
인터뷰의 상태까지 테스트하려면 또 따로 interview_id를 구해서 검증해야할 것 같아요!

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
> +    void createCommentByAll() {
1. 코치가 작성 -> 크루가작성 -> complete
2. 크루가 작성 -> 코치가 작성 -> complete

위 두 가지의 플로우 둘다 테스트가 있어야할 것 같습니다!

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +                .contains(COACH3.getNickname(), COACH2.getNickname(), COACH1.getNickname());
정렬된 면담목록 테스트여서 `containsExactly` 였는데 수정하신 이유가 있을까요?

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +        assertThatThrownBy(() -> interviewService.update(CREW1.getId(), 100L,
interview data.sql이 추가되면서 id가 바뀌었는데, 다음에도 이런 수정이 일어나지 않으려면 다른 방식으로 해결을 해야할 것 같아요!

0 혹은 -1로 테스트 하는 것이 어떨까요?

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +        assertThat(interviewResponseById.getStatus()).isEqualTo(InterviewStatusType.CREW_COMPLETED);
둘다 검증이 통과해야하먼 assertAll로 묶는게 좋아보여요!

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +        final Long interviewId = 10L;
얘도 마찬가지로 0이나 -1로 테스트하는게 어떨까요?

2022-08-14 06:21 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +    @DisplayName("존재하지 않는 면담에 코멘트를 작성하면 예외를 반환한다.")
코멘트 예외관련 테스트는 현재 interview service에 있는 검증책임이 comment로 간다면 comment 도메인에서 해야할 테스트로 보입니다!

2022-08-15 02:37 UTC, HyeonbinSa commented on backend/build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.22'
;; 이 부분이 어쩌다 들어간건지는 모르겠네요;; 아마 어노테이션을 등록하는 과정에서 추가된것 같은데 확인 후 삭제하도록 하겠습니다.

2022-08-15 02:38 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/comment/presentation/CommentController.java
> +    }
처음에 InterviewService에서 작업했기때문에 interviewId를 반환했습니다.
확인 감사합니다. Comment 기능 리팩터링 PR에서 수정된 부분입니다.

2022-08-15 02:38 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +    INVALID_STATUS_CREATE_COMMENT(HttpStatus.BAD_REQUEST, "해당 면담은 자유로운 한마디를 입력할 수 없습니다."),
리팩터링 PR에서 수정하도록 하겠습니다.

2022-08-15 02:39 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +
수달도 비슷한 리뷰를 해주셨는데 상황에  맞도록  네이밍 수정해보도록하겠습니다.

2022-08-15 02:40 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +        interview.complete(memberType);
좋습니다. 인터뷰 상태를 사용하는 메서드들을 본 뒤 수정하면 좋을 것 같습니다.

2022-08-15 02:41 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +    private MemberType getMemberType(final Long memberId) {
이 부분은 예전에 리뷰어에게 받았던 내용인데,
메서드 인자로 memberId를 받는 것을 아는데 메서드명에 넣는 것은 중복되지 않는가 라는 답변을 받은 적이 있습니다. 
제 개인적인 생각으로는 현재 네이밍을 유지하는 것도  좋을 것 같습니다.

2022-08-15 02:42 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +    }
추후에 Role이 추가됐을 경우를 가정하고 수정해보도록 하겠습니다.

2022-08-15 02:43 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
> +    }
하지만 현재 검증 로직이 CrewRepository나 CoachRespository를 사용하기때문에(왜냐하면 Member 클래스에는 Role이 없음) 분기문이 추가되는 상황은 어쩔 수 없는 것 같다고 생각합니다. 추가로 위에서 Interview에 관련되지 않은 사용자를 검증하는 로직이 있기 때문에 위와 같은 코드를 사용하였습니다.

2022-08-15 02:45 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/acceptance/InterviewAcceptanceTest.java
> +        assertThat(InterviewResponses).hasSize(3); // data.sql에 들어가있는 테스트 때문에 1 추가
data.sql에 추가하게된 이유는 현재 저희 서비스 로직 상으로 오늘 포함한 과거 시간의 예약이 불가능합니다. 그렇게때문에 과거 시간에 대한 Interview 예약을 테스트 코드에서 수행한다면 현재 Comment 기능이 아닌 예약 불가 시점에 대한 예외를 반환하게 됩니다.
그래서 data.sql에 미리 데이터를 넣어두는 방식을 택했습니다.

2022-08-15 02:46 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
> +public class CommentAcceptanceTest extends AcceptanceTest {
RestDocs적용은 아직 안했습니다;;;; 앤지가 공유해준 문서 보고 정리하도록 하겠습니다.

2022-08-15 02:46 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
> +    }
네 수정하도록 하겠습니다.

2022-08-15 02:48 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
> +    void createCommentByAll() {
우선,  서비스 테스트에서 비교적  많은 예외 상황을 테스트했기에  인수테스트에서는 코멘트 성공 관련  케이스만 테스트하였습니다.
시나리오  작성해서 테스트 추가하도록 하겠습니다.

2022-08-15 02:52 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +                .contains(COACH3.getNickname(), COACH2.getNickname(), COACH1.getNickname());
이 부분은 원복해두도록하겠습니다. 아마 data.sql에 데이터가 추가되면서 테스트 통과를 위해 임시 조치한 것으로 예상됩니다.

2022-08-15 02:52 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +        assertThatThrownBy(() -> interviewService.update(CREW1.getId(), 100L,
적용하도록하겠습니다.

2022-08-15 02:53 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +        assertThat(interviewResponseById.getStatus()).isEqualTo(InterviewStatusType.CREW_COMPLETED);
AssertAll 적용하도록하겠습니다.

2022-08-15 02:54 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> +    @DisplayName("존재하지 않는 면담에 코멘트를 작성하면 예외를 반환한다.")
적용하도록하겠습니다.

2022-08-15 09:12 UTC, Juhyung990122 reviewed
안녕하세요 바니! comment 구현 고생하셨습니다. 간단한 코멘트 남겼으니 확인 부탁드릴게요

2022-08-15 09:12 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/comment/presentation/CommentController.java
> +        return ResponseEntity.created(URI.create("/api/interview/" + interviewId)).build();
정확한 URI인가요?🤔 제 기억엔 interviews였던 것 같아서요!

2022-08-15 09:12 UTC, Juhyung990122 commented on backend/src/test/resources/data.sql
> +       ('2 : 질문 3입니다.', '2 : 답변 3입니다.', 2);
혹시 테스트 내에서 @BeforeEach가 아닌 data.sql을 활용하신 이유가 있을까요?

2022-08-15 13:11 UTC, soominsohn reviewed
안녕하세요 바니! 코멘트 기능 구현해주셔서 감사합니다.
간단한 네이밍 리뷰 한개 남겼습니다.
리뷰를 여기 남기는게 맞을까용...? 😄

2022-08-15 13:11 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/comment/presentation/CommentController.java
> +    public ResponseEntity<Void> createComment(@AuthenticationPrincipal final Long id,
`@AuthenticationPrincipal final Long id`
혹시 이 id가 memberId를 표현하신 걸까요?
의미가 명확하게 `memberId`로 바꿔보는건 어떨까요? 😄

2022-08-16 01:38 UTC, merged