[BE] refactor: 코치 되는시간 생성시 OPEN인 시간만 전부 삭제 후 PUT한다.
woowacourse-teams/2022-ternoko pull request #403
Opened 2022-09-21 16:18 UTC by dongho108

### Issues
- [ ] #400 
- [ ] #402 

### 논의사항
- 일단 급한 불은 껐습니다. 
- put할때 deleteAll, saveAll을 하는데, deleteAll 일때 OPEN인 경우에만 삭제되도록 했습니다.
- 현재 테이블 구조 문제점 발견
   -  interview가 AvailableDateTime id를 가지고 있어야할 것 같습니다.
   - 지금 구조에서 크루가 면담예약을 하면 USED로 바뀌고, 코치가 다시열면 OPEN 이 새로 생성되고. 또 다른 크루가 예약하면 USED가 됩니다. (USED, USED 두개 생성)
   - 그리고 또 OPEN으로 열면 하나가 더 생깁니다. (USED, USED, OPEN)
   - 이렇게 면담가능시간이 여러개가 생기는데 중요한건 availableDateTime이 coach만 알고있다보니까 어떤 인터뷰의 시간인지 모릅니다.
   - interview가 AvailableDateTime id를 가지고있다면 기존에 interviewStartTime으로 availableDateTime을 조회하던 것을 id기반 조회로 더 정확하고 빠른 조회가 가능할 것 같습니다.

close #400 
close #402

2022-09-28 06:41 UTC, her0807 requested changes
## 감사인사
QA 에서 발생했던 긴급한 문제였고, 또 품이 큰 작업이었는데, 맡아서 해주어서 고맙습니다. 😀

## DB 마이그레이션 필요
interview 에 availableDateTime 필드가 추가되면서 로직이 변경되었는데, 
현재 DB 의 칼럼이 추가되면서 기존 데이터에 대한 수동 변경이 필요할 것 같아요. 
시간을 잡아서 같이 변경해보시죠!

2022-09-28 06:41 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/support/time/TimeMachine.java
> +    private static Clock clock = Clock.systemDefaultZone();
Clock 도입 굿 👍🏻

2022-09-28 06:41 UTC, her0807 commented on backend/src/test/java/com/woowacourse/ternoko/support/fixture/refactor/AvailableDateTimeFixture.java
> +    public static final LocalDateTime _2022_07_03_12_00 = LocalDateTime.of(2022, 7, 3, 12, 0);
가독성 좋네요

2022-09-28 06:41 UTC, her0807 commented on backend/src/test/java/com/woowacourse/ternoko/service/InterviewServiceTest.java
> +        현재시간_이동(2022, 6, 20, 10, 0);
당일 예약, 취소와 같은 곳에서도 같은 메서드를 사용해서 시간 세팅을 하기 위해서 네이밍이 `현재 시간 이동`인 것 같은데
Local_date_time 의 시간을 설정해주는다는 느낌이  조금 부족한 것 같아요. 조금더 명시적으로 `현재_시간_세팅` 어떠십니까

2022-09-28 07:54 UTC, HyeonbinSa reviewed
애쉬!!  

도메인 구조가 변경되면서 수정하거나 고민할 부분이 많았을텐데 빠르게 구현해주셔서 감사드리니다.
테스트 픽스처가 훨씬 가독성이 좋아졌다고 생각이 드네요!!  Good!!!!!!!

몇가지 코멘트를 남겼는데 애쉬가 요청하신 중점적으로 리뷰하는 부분은 아니라 이후에  리팩터링으로 태스크를 분리해도 될 것 같아 언급만드립니다.

2022-09-28 07:54 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +    CANNOT_UPDATE_CREW(4007, "크루는 면담에서 변경할 수 없습니다."),
사용하는 곳을 보니 Interview 클래스에서 update할 때, 면담에 해당하는 Crew가 수정된 면담의 Crew와 같은지 아닌지를 비교하는 곳에 사용되고있습니다. 
"크루는 면담에서 변경할 수 없습니다."보다 "수정하려는 크루가 면담 신청자가 아닙니다."와 같이 수정해도 좋을 것 같아요.
이 부분은 리팩터링에 태스크를 분리해도 좋을 것 같아 지금 당장 적용하지 않아도 될  것 같습니다.

2022-09-28 07:54 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/Interview.java
> +    }
Interview 클래스 내에 있는 isCreatedBy() 메서드를 사용해서 이 부분을 제거할 수 있을 것 같습니다. 
동일한 사용자가 해당 면담에 대해 작업하는지에 대한 검증 같아서요.
```java
 public boolean isCreatedBy(final Long crewId) {
    return crew.isSameId(crewId);
}
```

2022-09-28 07:54 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/support/fixture/refactor/timemachine/ClockTest.java
> +}
EOL 처리가 필요할거같아요

2022-09-29 00:16 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
> +                    LocalDateTime.of(LocalDate.of(2022, 10, 25), LocalTime.of(11, 0)), AvailableDateTimeStatus.OPEN));
일단 테스트는 해봐야해서 달만 바꿔봤습니다.

그래서 테스트 돌릴때마다 현재 연, 월을 가져와 다음달의 시간을 열어주도록 수정하려고 했으나, 다음달의 주말이나 공휴일이 아닌 평일로 면담가능시간이 생성되도록 해야해서 또 리소스가 드는 것 같습니다.

추후에 DB Initializer도 완료된 면담이나 코멘트면담 등 여러가지 데이터를 포함한 initializer로 개선하는 방향이 좋을 것 같아요.

2022-09-29 00:18 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/availabledatetime/AvailableDateTimeRepository.java
> +
인터뷰에서 면담가능시간 id로 조회가 가능하여 안쓰는 쿼리이므로 삭제했습니다!
추가로 더 안쓰는 쿼리가 있다면 찾아서 삭제하겠습니다 감사합니다~

2022-09-29 00:28 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/Interview.java
> +
점진적 리팩토링을 위해서 필드를 추가하는 것으로 결정했습니다.
필드하나만 추가하는걸로 리팩토링하면 DB 마이그레이션을 먼저 진행해도 어플리케이션 코드가 수정되든 수정되지 않든 같은 코드로 돌아가서 운영서버에 반영하기 편할 것 같아요!

2022-09-29 00:31 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/Interview.java
> +        if (crew != interview.getCrew()) {
현재 인스턴스의 필드라면 get을 안하지만 다른 인스턴스의 필드라서 메서드를 통해 가져왔어요.
다른 인스턴스에서 꺼내오는 것이라 get으로 가져오는게 맞지 않나 싶네요.

왜냐면 getter가 구현되지 않았다면 다른 곳에서 노출되지 않기 위한 필드일텐데 그럴때 그냥 필드접근으로 가져오면 캡슐화가 깨진다고 생각해서 다른 인스턴스에서 가져올때는 메서드로 가져오는게 맞다고 생각했습니다~

2022-09-29 00:32 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/Interview.java
> +        this.availableDateTime = null;
와 근데 이부분은 정말 고민이 됩니다.
수달은 만약 null을 할당해주지 않으면 interview가 cancel될때 interview가 availableDateTime을 어떻게 가져야될거라고 생각하시나요?

2022-09-29 00:38 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/member/coach/Coach.java
> +@EqualsAndHashCode
좋은 피드백 감사합니다.
식별자로만 비교하는게 제일 좋아보여요!

2022-09-29 00:57 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/service/InterviewServiceTest.java
> +        현재시간_이동(2022, 6, 20, 10, 0);
좋습니다~

2022-09-29 00:58 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +    CANNOT_UPDATE_CREW(4007, "크루는 면담에서 변경할 수 없습니다."),
맞습니다~
예외처리관련부분도 리팩토링 예정이라 그때 같이하면 될거같아요!

2022-09-29 01:35 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/Interview.java
> +    }
대박입니다.. 반영했어요!

2022-09-29 01:42 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/member/coach/Coach.java
> +@EqualsAndHashCode
https://jwkim96.tistory.com/256

2022-09-29 03:24 UTC, her0807 approved these changes
고생하셨습니다 😀

2022-10-05 06:17 UTC, merged