[BE] fix: 다른 사람의 면담 조회 가능한 문제 해결
woowacourse-teams/2022-ternoko pull request #451
Opened 2022-10-06 01:48 UTC by HyeonbinSa

### Issues
- [ ] #445 

### 수정사항
- 기존
    - 면담 수정 페이지에서 InterviewId를 수정하면 내가 작성하지 않은 면담의 내용 정보를 확인할 수 있었습니다.
        - (참고) 면담 내용을 수정하는 경우에는 작성자가 아니라는 예외 반환했지만 면담 질문 내용이 노출되기 때문에 수정이 필요하다고 느꼈습니다.
- 수정
    - 면담에 해당하는 코치나 크루가 아님에도 조회하는 경우 예외를 반환합니다.

- 추가 메서드 
    - interview.validateOwnMember(Long memberId);

- 수정 후 테스트
<img width="472" alt="image" src="https://user-images.githubusercontent.com/36189291/194195579-f89b5856-b5a1-4fe4-a4a2-23b5bb3ba4d7.png">
본인의 면담이 아닐 경우 조회 불가

close #445

2022-10-06 04:32 UTC, HyeonbinSa commented
애쉬와 이야기해보니 조회하려는 사용자가 면담에 속하는 사람인지 검증하는 로직은 Service 계층에서 수행하는 것 맞다고 생각이 들어 수정하였습니다.

2022-10-06 14:48 UTC, dongho108 requested changes
중요한 기능인데 qa에서 찾자마자 반영해주셔서 감사합니다~
몇가지 코멘트 남겼는데 확인해주세요~!

### RCA룰
r : 반영해주세요!
c : 반영하지 않으셔도 되지만 고려해주세요.
a : 반영하지 않으셔도 괜찮습니다.

2022-10-06 14:48 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/application/InterviewService.java
> +        }
r: 이런식으로 도메인로직으로 옮겨보면 좋을 것 같아요

```suggestion
        if (!interview.containsMember(memberId)) {
            throw new InvalidInterviewMemberException(INVALID_INTERVIEW_BY_MEMBER);
        }
```

2022-10-06 14:48 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/service/InterviewServiceTest.java
> +                .isInstanceOf(InvalidInterviewMemberException.class);
r : 현재시간은 beforeEach에서 설정해주고 있어서 안해도 될거같아요.
위의 테스트코드는 전날예약이라서 시간을 이동해주고 있었습니다~

```suggestion
    void findInterview_WhenFindNotOwnInterview() {
        // given
        coachService.putAvailableDateTimesByCoachId(준.getId(), 면담가능시간생성요청정보_2022_07_01_10_TO_12);

        // when
        final Long interviewId = interviewService.create(허수달.getId(), 면담생성요청정보_준_2022_07_01_10_00);

        // then
        assertThatThrownBy(() -> interviewService.findInterviewResponseById(김록바.getId(), interviewId))
                .isInstanceOf(InvalidInterviewMemberException.class);
```

2022-10-07 01:11 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/service/InterviewServiceTest.java
> +                .isInstanceOf(InvalidInterviewMemberException.class);
given에 위치시킨 이유가 이 테스트에서 중점적으로 테스트하는 것이 findInterviewResponseById() 메서드를 통한 조회라고 생각해보았습니다. 그래서 given으로 위치시키고 "조회하고 예외가 발생하는 것"을 테스트하는게 when과 then이라고 생각했습니다.
이런 의도로 작성했는데 어떻게 생각하시나요   ??

2022-10-07 01:13 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/Interview.java
>       */
주석 제거했습니다.

2022-10-07 01:53 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/application/InterviewService.java
> +        }
말슴하신대로 Interview 내부로직으로 동작하게 수정하였습니다.

2022-10-07 01:55 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/service/InterviewServiceTest.java
> +
옙 지웠습니다.

2022-10-07 02:15 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/member/coach/Coach.java
> +@EqualsAndHashCode
오..  이런 문제점이 있었네요... 좋은 정보 감사합니다.
사용되던 어노테이션 지우고 JPA Utils에서 제공하는 equals, hashCode 메서드 오버라이딩하여 구현하였습니다.

2022-10-10 23:54 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/service/InterviewServiceTest.java
> +                .isInstanceOf(InvalidInterviewMemberException.class);
코치의 면담가능한 시간이 주어지고,
수달 면담이 생성되었을때,
록바가 수달면담을 조회하려고 시도하면 예외가 발생한다

는 상황이어서 when 을 저렇게 놓았습니다!

확실히 예외를 터뜨리는 상황이 검증하는 부분이라 헷갈릴 수 있긴 하네요..

아래 글 읽어보시고 바니가 판단해서 반영해주세요!

https://brunch.co.kr/@springboot/292

2022-10-11 00:05 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/member/coach/Coach.java
> +@EqualsAndHashCode
jpa utils라는게 있군요..

혹시 엔티티가 같으면 해시코드도 같나요?

2022-10-11 03:40 UTC, her0807 approved these changes
바니 수고하셨어요. 논의했던 내용이라, 로직 상 이상 없는지 위주로 확인했습니다. 😀

2022-10-11 03:40 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/core/domain/member/coach/Coach.java
>  }
entity 의 equals and hashCode 사용시 유의할 점을 한번 봐볼까요 ?

https://velog.io/@park2348190/JPA-Entity%EC%9D%98-equals%EC%99%80-hashCode

2022-10-11 03:40 UTC, her0807 commented on backend/src/test/java/com/woowacourse/ternoko/core/domain/interview/InterviewTest.java
> +        assertTrue(interview.containsMember(5L));
테스트 코드 꼼꼼하게 잘 작성해주셨네요 ㅎㅎ 
CREW1.getId() 를 해서 추후 ID 가 변경될 때 유연하게 대처하고, 명시적으로 CREW1 의 Id 임을 나타내는건 어떨까요 ?

2022-10-11 05:24 UTC, merged