[BE] refactor: 중복된 멤버 이름으로 닉네임 수정 시 검증 로직 추가
woowacourse-teams/2022-ternoko pull request #452
Opened 2022-10-06 03:55 UTC by soominsohn

### Issues
- [ ]  #330 

### 논의사항
- coachService, crewService에 멤버 이름 중복여부 판단하는 예외 추가했습니다.
- sql exception을 catch 후 400번대 에러를 반환 하려다가 다른 예외가 터질 때 파악하기 어려울 것 같아 검증 로직 추가하는 방향으로 진행하였습니다. 혹시 이 방법 괜찮은지 피드백 주시면 감사하겠습니다.
- custom exception 사용법 이렇게 하는게 맞는지 궁금하네요...

close #330

2022-10-06 04:53 UTC, HyeonbinSa requested changes
앤지, 빠르게 이슈 처리해주셔서 감사합니다.
성공, 실패 테스트 케이스까지 구현한 부분 좋았습니다. 간략하게 리뷰 남겨보았는데 확인 부탁드릴게요.

2022-10-06 04:53 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
> +    public void partUpdateCoach(final Long coachId, final CoachUpdateRequest coachUpdateRequest) {
이름이 잘못되어있었네요. 회원 정보 수정에 대한 메서드니까 여기서 네이밍 수정해도 좋을 것 같습니다.

2022-10-06 04:53 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
> +        }
이 부분이 닉네임 중복 검증 로직인 것 같네요. 
이건 단순히 제 개인적인 생각이라 참고만 해주셔도 될 것 같아요.
현재 검증 로직에서는 Interview 안에 있는 Domain에서 한번, memberRepository에서 중복 체크 한번해서 총 두번 검증을 통해 닉네임 중복 검사를 수행하고 있는데 @Query를 사용하여 한 번에 검사하는 방식은 어떨까 생각이 들었습니다.
예를 들어서 `@Query(select * from member whrere nickname = :nickname and id <> :memberId)`와 같이 사용할 수도 있을 것 같아요. 
저는 지금 방식도 좋다고 생각하고 위와 같은 방법도 있을 것 같아 말씀드려보았습니다.

2022-10-06 04:53 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/presentation/CoachController.java
> +        coachService.partUpdateCoach(coachId, coachUpdateRequest);
Method 명이 잘못되었던 부분 잘 찾아주셨네요

2022-10-06 04:53 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
> +    public void partUpdateCoach(final Long coachId, final CoachUpdateRequest coachUpdateRequest) {
수정했으니 TODO는 지워도 될 것 같아요.

2022-10-06 15:13 UTC, dongho108 requested changes
고생하셨습니다 앤지 ㅎㅎ

앤지는 검증로직만 추가하려고 했는데 레거시부분들까지 리뷰남기게 됐네요..ㅠ
운영중인 서비스에서 리팩토링하려면 이럴때 조금씩 개선하는 것이 좋을 것 같아서 이렇게 리뷰 남겼습니다.

본인이 짰던 코드가 아니라서 리팩터링하기 꽤 낯설텐데 구현 담당했던 바니, 수달이랑 얘기해보면서 수정하면 좋을 것 같아요.
아니면 맡겨도 될 것 같구요!

### RCA 룰
r : 반영해주세요!
c : 반영하지 않으셔도 되지만 고려해주세요.
a : 반영하지 않으셔도 됩니다 개인적인 의견이에요!

2022-10-06 15:13 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CrewService.java
> +        }
c : 검증로직은 메서드로 분리하면 더 좋을 것 같습니다!

2022-10-06 15:13 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CrewService.java
> +                && memberRepository.existsByNickname(request.getNickname())) {
c : 조건절도 좀 길어서 가독성있게 바꿔보면 좋을 것 같아요

```suggestion
        if (isDuplicatedNickname(crew, requestNickname)) {
```

2022-10-11 02:41 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
> +        }
오 @Query를 사용하면 레포지토리를 한번만 접근 할 수 있겠군요.
`SELECT COUNT (m.id) > 0 FROM Member m WHERE m.nickname = :nickname AND m.id <> :memberId` 말씀해주신 쿼리에서 COUNT 값이 0 이상인지 판별하여 boolean 반환하도록 수정했습니다. 감사합니다 😄

2022-10-11 02:45 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
> +        }
저도 이 고민을 해보았는데요
1. 중복을 체크하고 예외를 던지는 로직을 memberSerivce로 옮기고 각각 서비스가 memberService를 의존하게 한다.
2. 중복을 냅두고 서비스-서비스 의존관계를 만들지 않는다.

전 2번을 선택했었습니다.
현재 Coach의 update 로직의 경우 introduce 칼럼으로 인해 memberService에서 공통적으로 update 요청을 날리지 못하겠더라구요.
혹시 제가 알지 못하는 다른 방법이 있을까요? 애쉬가 생각하신 중복 줄이는 방법을 알려주세용! 도와주십쇼~ 😄

2022-10-11 02:46 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CrewService.java
> +        }
검증 로직을 @Query로 빼두었는데 현재 상황에서도 분리하면 좋을까요?

2022-10-11 02:48 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
> +    public void partUpdateCoach(final Long coachId, final CoachUpdateRequest coachUpdateRequest) {
반영했습니다 👍

2022-10-13 06:36 UTC, HyeonbinSa approved these changes

2022-10-14 16:30 UTC, merged