FE] refactor: 코치 시간 생성 달력과 크루 시간 선택 달력을 분리한다.
woowacourse-teams/2022-ternoko pull request #458
Opened 2022-10-07 07:31 UTC by sanaandmomo

### Issues
- [ #453 ] 

### 논의사항

close #453

2022-10-11 00:44 UTC, lokba requested changes
안녕하세요 놀드~ 주말 잘 쉬셨나요? 

리팩토링 하신 부분 잘 봤습니다. 고생하셨습니다. 관심사가 분리되니 정말 코드 보기 편하네요. 수고하셨어요.
코멘트는 RCA룰을 적용해서 남겨봤습니다. 코멘트 한번 확인해주세요.

추가적으로, 기능 정상 작동 확인했습니다. 

### RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2022-10-11 00:44 UTC, lokba commented on frontend/src/components/@common/Calendar/index.tsx
> +const Calendar = ({ children }: CalendarProps) => {
a : 필요한 내용만 공통으로 잘 빼신것 같아요👍

2022-10-11 00:44 UTC, lokba commented on frontend/src/components/@common/CommonCrewAndCoachCalendarStyle/styled.tsx
> +import styled, { css, keyframes } from 'styled-components';
c : `@common` 폴더 하위에 있어서 파일명에 Common을 제외해도 되지 않을까요?

2022-10-11 00:44 UTC, lokba commented on frontend/src/components/CoachCreateTimeCalendar/index.tsx
> +  const isDateNotInOfSelectedDatesAfterToday = (day: number) =>
c : 리팩토링 과정에서 가독성을 위해 함수명까지 바꾸셨네요. 의미상으로 봤을때, 오늘 날짜이후로 day(매개변수)가 selectedDate에 포함 안되었느냐? 인 것 같습니다. 함수명에 `in`과 `of` 전치사가 두 개 쓰였는데, 의미상으로는 `of`을 제거해도 될 것 같습니다.

2022-10-11 00:44 UTC, lokba commented on frontend/src/components/CoachScheduleCalendar/index.tsx
> +  const [babyModalPosition, setBabyModalPosition] = useState<ModalPositionType>({});
c : ModalPositionType 사용처를 훑어보니까, babyModal에서만 쓰이는 것 같네요. 타입에 대한 네이밍도 `BabyModalPositionType`으로 변경하는 것이 어떨까요?

2022-10-11 00:44 UTC, lokba commented on frontend/src/components/CoachScheduleCalendar/index.tsx
> +export default CoachScheduleCalendar;
c : CoachCreateTimeCalendar, CrewApplyInterviewCalendar에서는 memo를 감쌌는데, 해당 컴포넌트에서는 왜 안 감쌌는지 의도하신 걸까요?

2022-10-11 00:44 UTC, lokba commented on frontend/src/components/CrewApplyInterviewCalendar/styled.tsx
> +export const WeekDay = styled.div`
r : 
CommonCrewAndCoachCalendar
사용처 - CrewApplyInterviewCalendar, CoachCreateTimeCalendar

WeekDay, Days가 중복적으로 쓰이는 곳
사용처 - CrewApplyInterviewCalendar, CoachCreateTimeCalendar

결론 : WeekDay와 Days을 CommonCrewAndCoachCalendar으로 옮기는 게 어떨까요?

2022-10-11 00:44 UTC, lokba commented on frontend/src/utils.ts
> +export const convertMonthIndexToMonth = (monthIndex: number): CalendarTime['month'] =>
a : 고생했어요 👍

2022-10-14 08:20 UTC, sanaandmomo commented on frontend/src/components/CoachScheduleCalendar/index.tsx
> +  const [babyModalPosition, setBabyModalPosition] = useState<ModalPositionType>({});
수정했어요.

2022-10-14 08:20 UTC, sanaandmomo commented on frontend/src/components/CoachScheduleCalendar/index.tsx
> +export default CoachScheduleCalendar;
수정했어요.

2022-10-14 08:23 UTC, sanaandmomo commented on frontend/src/components/CoachCreateTimeCalendar/index.tsx
> +  const isDateNotInOfSelectedDatesAfterToday = (day: number) =>
수정했어요.

2022-10-14 09:33 UTC, merged