[BE] Custom exception 을 리팩터링한다.
woowacourse-teams/2022-ternoko pull request #463
Opened 2022-10-11 10:16 UTC by her0807

### Issues
- [ ] #462 

### 논의사항
도메인당 하나의 InvalidException 을 만들어서 진행한다. 

close #462

2022-10-12 15:29 UTC, dongho108 approved these changes
이대로 처리하면 예외처리 컨벤션이 갖춰질 것 같아요
기존의 사용하던 비즈니스 코드들도 차근차근 리팩토링 하면될 것 같습니다
고생하셨어요!

2022-10-13 01:45 UTC, HyeonbinSa requested changes
수달! CustomException 리팩터링 해주셔서 감사합니다.

Exception 관리 포인트가 ExceptionType 클래스 하나로 줄어든 것 같아서 보다 편해졌다고 느껴지네요! 굳!

2022-10-13 01:45 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +    UNHANDLED_EXCEPTION(null, 9999, "예상치 못한 예외입니다.");
이 부분은 null보다 500번대 에러를 던져주는 것은 어떨까요?

2022-10-13 01:45 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +    REQUEST_EXCEPTION(null, 8001, "http 요청 에러입니다."),
현재 사용하지 않는 Exception인 것 같습니다.
이후에 사용하면 좋을 것 같지만 현재 특정 HttpStatusCode가 명확하지 않아 정해진 뒤에 추가하면 좋을 것 같아요!!

2022-10-15 01:12 UTC, merged

2022-10-15 01:12 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +    UNHANDLED_EXCEPTION(null, 9999, "예상치 못한 예외입니다.");
바니 ~ ㅎㅎ 놓쳤던 부분인데 확인해주셔서 감사합니다. ㅎㅎ

2022-10-15 01:13 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +    REQUEST_EXCEPTION(null, 8001, "http 요청 에러입니다."),
이부분은 제거해두었다가, 필요할 때 추가하는게 좋겠네요  꼼꼼한 피드백 감사합니다. ☺️👍🏻