[BE] refactor: 완료한 인터뷰를 삭제할 수 있게 변경한다.
woowacourse-teams/2022-ternoko pull request #486
Opened 2022-10-17 06:47 UTC by soominsohn

### Issues
- [ ] #484 

### 논의사항
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/83059234/196107336-b5fc0d6c-8340-4e01-a9ff-aeaead924d67.png">

인터뷰 삭제 시 comment 삭제가 같이 되지 않아 생긴 FK 문제였습니다!

- 현재 service에서 코멘트까지 삭제 했는데, 얘를 혹시 JPA단에서 delete cascade로 해결하는 방법 아시는분 계실까용?

close #484

2022-10-17 07:22 UTC, dongho108 commented
manyToOne 이라 cascade는 못걸고 앤지가 한 방식이 맞을 것 같아요
cascade할거면 양방향해야하는데 우리 이제 양방향 하지말죠 ㅋㅋ;

자세한건 확인하고 리뷰 달겠습니다!

2022-10-19 02:36 UTC, dongho108 requested changes
고생하셨습니다 앤지~!
몇가지 코멘트 남겼습니다!! 반영해주세요!

2022-10-19 02:36 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/application/InterviewService.java
> +    private void deleteComment(Long crewId, Interview interview) {
r: 파차차

```suggestion
    private void deleteComment(final Long crewId, fianl Interview interview) {
```

2022-10-19 02:36 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/application/InterviewService.java
> +    }
c: interview id로 코멘트 조회하고 그 id로 삭제하는 방식이 더 나을 것 같다는 생각이 들어요!

2022-10-19 02:36 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/core/application/InterviewService.java
>      public void delete(final Long crewId, final Long interviewId) {
r: 완료된 인터뷰 삭제 테스트도 필요할 것 같아요!

2022-10-20 05:39 UTC, soominsohn commented
기능 변경으로 close합니다 😃

2022-10-20 05:39 UTC, closed without merging