[BE] Slack 로그인 기능 구현
woowacourse-teams/2022-ternoko pull request #71
Opened 2022-07-19 10:53 UTC by HyeonbinSa

### Issues
- [x] #57 

### 논의사항

close #57

2022-07-20 00:42 UTC, dongho108 requested changes
어려운 슬랙로그인 구현하느라 고생하셨습니다!!!
아직은 같이 확인해야할 사항들이 있는 것 같아서 request changes로 할게요

2022-07-20 00:42 UTC, dongho108 commented on backend/src/main/resources/application-local.yml
>    h2:
local은 h2로 돌리기로 했어서 해당 yml 설정은 바꾸면 안될 것 같아요
각자 로컬에 mysql 설치하고 `create database ternoko;`만 해주시면 로컬로 돌아갈거에요!
안되시면 말씀해주세요! 리드미에도 적어놔야겠네용

```suggestion
    url: jdbc:mysql://localhost:3306/ternoko?serverTimezone=Asia/Seoul
    username: root
    password:
```

2022-07-20 00:42 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +        // 로그인인지, 회원 가입인지 갈래
주석은 읽다가 헷갈릴까봐 일부러 넣어놓으신 걸까요?

2022-07-20 00:42 UTC, dongho108 commented on backend/src/main/resources/application.yml
> +      secret-key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno'
private하게 관리할 자원들은 환경변수 혹은 github secrets로 설정하는 방법을 고민해봐야될 것 같아요
이대로는 공개되면 위험할 것 같아요
오늘 secret key 관련 설정들 알아보고 알려드리겠습니다!

2022-07-20 00:43 UTC, dongho108 commented
그리고 커밋이력이 custum exception 도입과 연결되어있어서 rebase 하시고 다시 푸시해주셔야 할 것 같아요!

2022-07-20 08:13 UTC, her0807 commented on backend/src/main/resources/application.yml
> +      secret-key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno'
이건 새로운 이슈로 가져가면 좋을 것 같아요 👍🏻

2022-07-20 08:14 UTC, her0807 commented on backend/src/main/resources/application.yml
> +      secret-key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno'
수정하면서 키값도 새로 발급 받을 예정입니다. 신경써주시는 덕분에 든든합니다 !!! 💪🏻

2022-07-20 08:14 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +        // 로그인인지, 회원 가입인지 갈래
일부러 넣어놨는데, 메서드 명으로도 확인이 가능한 것 같아서 삭제하겠습니다!!!

2022-07-20 16:05 UTC, her0807 requested changes

2022-07-20 16:05 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +}
<img width="658" alt="스크린샷 2022-07-21 오전 1 01 03" src="https://user-images.githubusercontent.com/26570275/180029031-3d6c1463-22bf-4f80-9bfc-4dc1655ced62.png">

2022-07-20 16:05 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +}
https://gracelove91.tistory.com/100

2022-07-21 05:43 UTC, Juhyung990122 reviewed
슬랙로그인 구현하시느라 두분 다 고생많으셨습니다! 간단한 코멘트들 남겼으니 확인해주세요ㅎㅎ

2022-07-21 05:43 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +                       JwtProvider jwtProvider,
final을 붙이지 않은 이유가 있을까요?:)

2022-07-21 05:43 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +    private OpenIDConnectUserInfoResponse getUserInfoResponseBySlack(String code)
파차차!

2022-07-21 05:43 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +            return jwtProvider.createToken(String.valueOf(member.get().getId()));
```suggestion
memberRepository.findByEmail(userInfoResponse.getEmail())
                .ifPresent((foundMember) -> jwtProvider.createToken(String.valueOf(foundMember.getId())));
```
이렇게는 어떠신가요?

2022-07-21 05:43 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +        return userInfoResponse;
```suggestion
        return slackMethodClient.openIDConnectUserInfo(userInfoRequest);
```
바로 리턴해도 좋을 것 같아요!

2022-07-21 05:43 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +        return openIDConnectTokenResponse;
얘도 바로 리턴할까요?

2022-07-21 05:43 UTC, Juhyung990122 commented on backend/src/main/java/com/woowacourse/ternoko/common/AuthInterceptor.java
> +	}
인터셉터와 프로바이더 내의 파이널을 한번 더 점검해보아요:)!

2022-07-21 05:43 UTC, Juhyung990122 commented on backend/src/test/java/com/woowacourse/ternoko/service/AuthServiceTest.java
> +		String accessToken = authService.login(code);
파차차!

2022-07-25 01:17 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/common/JwtProvider.java
> +			throw new ExpiredTokenException(ExceptionType.EXPIRED_TOKEN);
`claims.getBody().getExpiration().before(new Date());` 코드의 결과가 무시되고 있는 것 같아요!
혹시, 토큰의 만료 기간을 검증하고 예외를 발생하는 로직이었을까요?

그렇다면
```suggestion
		try {
            final Jws<Claims> claims = Jwts.parser().setSigningKey(key).parseClaimsJws(token);
            final boolean expired = claims.getBody().getExpiration().after(new Date());
            if (expired) {
                throw new ExpiredTokenException(ExceptionType.EXPIRED_TOKEN);
            }
```

다음과 같은 방법에 대해선 어떻게 생각하시나요?

2022-07-25 01:17 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/GlobalControllerAdvice.java
> +	}
CustomException을 잘 적용시켜 ControllerAdvice에 적용시켜 주었군요!

예외에 대한 ResponseEntity를 반환할 때,
status코드를 badRequest()와 같이 명시적으로 적는 것보다.
다음과 같이 status code를 `ExceptionType` Enum클래스에서 정의한 code 를 사용한다면, statusCode 변경이 일어날 경우 변화에 유연하게 대처할 수 있을 것 같아요 😄 

```
return ResponseEntity
                .status((e.getCode())
                .body(new ExceptionResponse(e.getCode(), e.getMessage()));
```

2022-07-25 01:17 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +	private final int code;
ExceptionType의 status code를 나타내는 필드이군요!
혹시 필드 이름을 `private final int code;` 보다 `private final int statusCode;`로 변경해 http 메서드의 상태코드라는 것을 명확히 나타내면 어떨까요?
CustomException의 경우, 프로젝트 내에서 팀과의 소통을 위해 만든 error code가 생기는 경우가 있습니다. 
이럴경우 http status code와 error code 필드가 헷갈릴 수 있을것 같아서요! 😄

2022-07-25 01:17 UTC, soominsohn commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
> +	UNAUTHORIZED_MEMBER(401, "토큰이 존재하지 않습니다.");
http status code를 400, 401로 표현해 주셨군요!
혹시 code 필드를 int형이 아닌 HttpStatus enum 타입으로 대체하고,
각 status code를 HttpStatus.NOT_FOUND와 같이 변경해 보는 것은 어떨까요?
status code에 대한 조금 더 명확한 소통이 가능할 것 같습니다!

2022-07-25 02:44 UTC, dongho108 requested changes
바니, 수달 어려운 slack 로그인 구현하느라 정말 고생 많으셨어요...!!!

jwt 토큰관련돼서 리뷰 남겼는데 이부분은 같이 확인이 필요할 것 같아서 request changes로 할게요!!

2022-07-25 02:44 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/common/JwtProvider.java
> +			claims.getBody().getExpiration().before(new Date());
앤지말처럼 무시되던 before()를 아래와 같이 expired 검증을 추가하니 테스트 코드가 깨지네요! 같이 한번 알아보면 좋을것 같아요

```suggestion
	if (!claims.getBody().getExpiration().before(new Date())) {
		throw new ExpiredTokenException(EXPIRED_TOKEN);
	}
```

2022-07-25 02:44 UTC, dongho108 commented on backend/src/main/java/com/woowacourse/ternoko/common/JwtProvider.java
> +			Jws<Claims> claims = Jwts.parser().setSigningKey(key).parseClaimsJws(token);
gradle 보니까 `jwt 0.11.5` 버전을 가져오셨네요!
그래서 알아보니 0.11.5 버전에서는 `parser`가 아니라 `parserBuilder`로 `claims`를 생성하는 것 같아요
```suggestion
final Jws<Claims> claims = Jwts.parserBuilder()
		.setSigningKey(key)
		.build()
		.parseClaimsJws(token);
```

참고 : https://javadoc.io/static/io.jsonwebtoken/jjwt-api/0.11.2/io/jsonwebtoken/JwtParserBuilder.html

2022-07-25 02:44 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/service/AuthServiceTest.java
> +public class AuthServiceTest {
auth 관련돼서 슬랙 로그인후 토큰을 받아오는 과정의 대한 테스트만 존재하는 것 같아요!

위에서 토큰 expired 검증이 깨지는 것을 확인하기 위해서라도 jwt 자체에 대한 테스트가 있어야할 것 같아요!

2022-07-25 12:42 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +        return userInfoResponse;
디버깅 하려고 추출했다가 변경을 안했네요 ㅠㅠ

2022-07-26 00:07 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/common/JwtProvider.java
> +			throw new ExpiredTokenException(ExceptionType.EXPIRED_TOKEN);
claims 내에 있는 메서드를 처음 써봐서, 제대로 파악을 하지 못하고 작성했던 것 같아요. 🥲 덕분에 해당 메서드에 대한 이해도가 높아져서 아주 좋네요 👍🏻

2022-07-26 00:09 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/GlobalControllerAdvice.java
> +	}
오오 좋은 관점이네요 👍🏻

2022-07-26 07:25 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/common/JwtProvider.java
> +			throw new ExpiredTokenException(ExceptionType.EXPIRED_TOKEN);
다시 확인해보니까 parseClaimsJws 하는 과정에서 메서드를 호출하는 시점에 클레임이 만료된 경우 
`ExpiredJwtException` 을 던져 주네요.  위 로직 자체가 없어도 되겠어요. 


> <img width="635" alt="스크린샷 2022-07-26 오후 4 22 59" src="https://user-images.githubusercontent.com/26570275/180947942-380ae4dc-057a-484a-8f50-484a90cbfedc.png">
,

2022-07-27 06:08 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/common/exception/BadRequestException.java
> +    private final HttpStatus code;
`HttpStatus`로 바꾼 부분 좋네요!! Good💪🏼

2022-07-27 06:56 UTC, HyeonbinSa reviewed
로그인 기능 구현하느라고 고생  많으셨습니다. 코드 살펴보면서 리뷰 몇개 작성해보았습니다.

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/controller/AuthController.java
> +        return ResponseEntity.ok().body(loginResponse);
```java
return ResponseEntity.ok(loginResponse);
```
HTTP  Method OK일 경우 위와 같이 작성할 수 있습니다!

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/dto/request/CrewUpdateRequest.java
> +    private String imagUrl;
오타가 있네요 ㅎㅎ `imageUrl`

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/controller/MemberController.java
> +    public ResponseEntity<NicknameResponse> checkUniqueNickname(@PathVariable String nickname) {
전체적인 Controller 분리!! 명확하게 분리해주셨네요. 감사합니다

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/controller/MemberController.java
> +    public ResponseEntity<NicknameResponse> checkUniqueNickname(@PathVariable String nickname) {
메서드 이름을 봤을 때 `닉네임 중복 검사`하는 메서드로 보입니다.
닉네임을 받아 올때 login의 계층이 아닌 중복 검사를 하는 대상으로 사용되기 때문에 Path Variable 대신 Query로 받아오는게 좋겠다는 생각이 듭니다.
`/login/check?nickname={nickname}`과 같은 형태는 어떨까요??

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/domain/member/Member.java
> +    @Column(length = 5, unique = true)
글자수 제한, 빠르게 적용해주셨네요.  감사합니다.

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/dto/LoginResponse.java
> +    private boolean isSignup;
닉네임을 입력받기 위해 사용하는 데이터이니 `hasNickname`으로 바꾸면 좋을 것 같습니다.

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +        boolean isSignup = member.get().getNickname().isEmpty();
여기도 `hasNickname`이 좋을 것 같습니다.

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
> +            return LoginResponse.of(Type.COACH, jwtProvider.createToken(String.valueOf(coach.getId())), true);
`hasNickname`이라면 회원 가입 시에는 닉네임이 없기때문에  `false`가 되겠네요.

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/main/java/com/woowacourse/ternoko/service/CoachService.java
> +                .map(CoachResponse::from)
훨씬 깔끔하네요!! Good

2022-07-27 06:56 UTC, HyeonbinSa commented on backend/src/test/java/com/woowacourse/ternoko/common/JwtProviderTest.java
> +class JwtProviderTest {
JwtProvier  테스트 해주셨네요. 좋습니다

2022-07-27 07:58 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/controller/AuthController.java
> +        return ResponseEntity.ok().body(loginResponse);
감사합니다 :)

2022-07-27 08:07 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/controller/MemberController.java
> +    public ResponseEntity<NicknameResponse> checkUniqueNickname(@PathVariable String nickname) {
@HyeonbinSa Path Variable  와 Query 모두 데이터를 받아오는 것은 같은데 어떤 차이가 있을까요 ?

2022-07-27 08:08 UTC, her0807 commented on backend/src/main/java/com/woowacourse/ternoko/controller/MemberController.java
> +    public ResponseEntity<NicknameResponse> checkUniqueNickname(@PathVariable String nickname) {
좋네요 ✨

2022-07-27 08:58 UTC, Juhyung990122 approved these changes

2022-07-27 08:59 UTC, soominsohn approved these changes

2022-07-27 11:27 UTC, her0807 approved these changes

2022-07-27 11:28 UTC, dongho108 approved these changes
진짜 로그인 구현하느라 고생 많이하셨어요!!!!!
리뷰드린거 반영 다 된거 확인해서 approve 하겠습니다~!

2022-07-27 11:28 UTC, dongho108 commented on backend/src/test/java/com/woowacourse/ternoko/service/AuthServiceTest.java
> +    JwtProvider jwtProvider;
여기도 private 붙여주면 좋을 것 같아요!

2022-07-27 11:28 UTC, dongho108 commented on backend/src/test/resources/application-test.yml
> +spring:
application-test.yml을 지워도 잘 돌아가네요!
AuthServiceTest의 ActiveProfiles("test")까지 같이 지워도 잘 돌아갑니당!

2022-07-27 11:28 UTC, dongho108 commented on backend/src/test/resources/application.yml
> +
application-test.yml의 
```
server:
  ssl:
    key-store: classpath:ternoko-keystore.p12
    key-store-type: PKCS12
    key-store-password: 980807
    key-alias: ternoko-keystore
```
를 가져오면 acceptance테스트가 깨지고 안가져오면 안깨지네요
왜그런지 같이 알아보면 좋을 것 같아요

2022-07-27 11:28 UTC, dongho108 commented on backend/src/test/resources/application.yml
> +
test yml에서 classpath를 다르게 인식하는 것 같아용!
https://velog.io/@_anna/classpath

2022-07-27 11:28 UTC, merged